version: 2
project_name: ssbak


release:
  github:
    owner: stupid-simple
    name: backup

builds:
  - id: ssbak
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    binary: ssbak

archives:
  - format: tar.gz
    name_template: ssbak-{{ .Version }}-{{ .Os }}-{{ .Arch }}

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

dockers:
  - image_templates:
      - "ghcr.io/stupid-simple/backup:{{ .Tag }}-amd64"
      - "ghcr.io/stupid-simple/backup:v{{ .Major }}-amd64"
      - "ghcr.io/stupid-simple/backup:v{{ .Major }}.{{ .Minor }}-amd64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
    extra_files:
      - entrypoint.sh
  - image_templates:
      - "ghcr.io/stupid-simple/backup:{{ .Tag }}-arm64"
      - "ghcr.io/stupid-simple/backup:v{{ .Major }}-arm64"
      - "ghcr.io/stupid-simple/backup:v{{ .Major }}.{{ .Minor }}-arm64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
    goarch: arm64
    extra_files:
      - entrypoint.sh

docker_manifests:
  - name_template: "ghcr.io/stupid-simple/backup:latest"
    image_templates:
      - "ghcr.io/stupid-simple/backup:{{ .Tag }}-amd64"
      - "ghcr.io/stupid-simple/backup:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/stupid-simple/backup:{{ .Tag }}"
    image_templates:
      - "ghcr.io/stupid-simple/backup:{{ .Tag }}-amd64"
      - "ghcr.io/stupid-simple/backup:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/stupid-simple/backup:v{{ .Major }}"
    image_templates:
      - "ghcr.io/stupid-simple/backup:v{{ .Major }}-amd64"
      - "ghcr.io/stupid-simple/backup:v{{ .Major }}-arm64"
  - name_template: "ghcr.io/stupid-simple/backup:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/stupid-simple/backup:v{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/stupid-simple/backup:v{{ .Major }}.{{ .Minor }}-arm64"

changelog:
  use: github